# Generated by Django 5.2 on 2025-05-08 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная'), ('system', 'Системная')], default='system', max_length=20, verbose_name='Тема оформления')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='ru', max_length=10, verbose_name='Язык интерфейса')),
                ('enable_notifications', models.BooleanField(default=True, verbose_name='Включить уведомления')),
                ('show_completed_tasks', models.BooleanField(default=True, verbose_name='Показывать завершенные задачи')),
                ('default_page_size', models.IntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default=25, verbose_name='Размер страницы по умолчанию')),
                ('email_notifications', models.BooleanField(default=False, verbose_name='Уведомления по электронной почте')),
                ('auto_refresh_cache', models.BooleanField(default=True, verbose_name='Автоматическое обновление кэша')),
                ('conversation_history_limit', models.IntegerField(default=30, help_text='Через сколько дней архивировать старые беседы', verbose_name='Лимит истории бесед (дней)')),
                ('export_analytics', models.BooleanField(default=True, verbose_name='Разрешить экспорт аналитики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
        migrations.RemoveIndex(
            model_name='analyticsevent',
            name='chat_analyt_user_id_6b7357_idx',
        ),
        migrations.AddIndex(
            model_name='aimodelmetrics',
            index=models.Index(fields=['day'], name='chat_aimode_day_f9939b_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'timestamp'], name='chat_analyt_user_id_afa211_idx'),
        ),
        migrations.AddIndex(
            model_name='usermetrics',
            index=models.Index(fields=['day'], name='chat_userme_day_ef89e0_idx'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='ai_model_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by_users', to='chat.aimodel', verbose_name='Предпочитаемая модель ИИ'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
