# Generated by Django 5.2 on 2025-05-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='processing_time',
            field=models.FloatField(default=0.0, verbose_name='Время обработки (сек)'),
        ),
    ]
