# Generated by Django 5.2 on 2025-05-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_ai_models'),
        ('chat', '0002_auto_20250509_2105'),
    ]

    operations = [
    ]
